package com.smartcare.model;

public enum NotificationType {
    APPOINTMENT_CONFIRMATION,
    APPOINTMENT_REMINDER,
    APPOINTMENT_CANCELLATION,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    INVOICE_GENERATED,
    INVOICE_OVERDUE,
    MEDICATION_REMINDER,
    HEALTH_ALERT,
    SYSTEM_NOTIFICATION
} 